### ISSUE TITLE
Prueba de usabilidad Bias Correction

### ISSUE THREAD

**Issue by cenavarror** [CCAFS/CCAFS-Climate#34]
Probar con al menos 5 usuarios seleccionados el funcionamiento de las interfaces Bias Corrrection y Weather Stations. 

Apoyarnos con Sebastián Amariles quién ha hecho algunas pruebas de usabilidad anteriormente. Opcional, diseñar con él una breve encuesta con calificaciones de 1 a 5 y algunas preguntas abiertas, incluyendo:
¿Cuán intuitivo es?
¿La ubicación de los botones es la adecuada?
¿Qué le cambiaría?
Otras... 

Usuarios propuestos: Sebastián Amariles, Héctor Tobón, Lizeth Llanos, Patricia Moreno, Jefferson Rodríguez, David Arango, Camilo Barrios, Diego Agudelo, Jeison Mesa y Harold Achicanoy, Steven Sotelo y Edward Guevara 

Idealmente pedir de antemano 15 minutos del tiempo de cada uno e ir hasta sus sitios de trabajo para efectuar la prueba allí.

**Comment by sebas932** [comment]
Hola Carlos, mira, este es un test que hice hace mucho para AMKN, quizás te pueda ser util.
https://docs.google.com/document/d/1joLqUzN34k2xnymot-A9yfYRDIZh5HWCQE34XJxogFQ/edit?usp=sharing

**Comment by cenavarror** [comment]
Me parece muy bueno, gracias Sebas. 
Jaime - Creo que podemos tomar algunas de las preguntas e incluirlas en la nuestra.

**Comment by cenavarror** [comment]
Realizado y analizado!
