### ISSUE TITLE
Mostrar los filtros que ha seleccionado el usuario

### ISSUE THREAD

**Issue by hernandcb** [CCAFS/CCAFS-Climate#8]
Seria bueno poder mostrar en algun lado del un texto donde se muestren cuales son las opciones elegidas por el usuario. Carlos y yo pensamos en agregar algo como:

Cordex > Regional > BaseLine > ncar_ccsm3_0 

Pero no estamos seguros de en qué lugar quedaria bien.

**Comment by jheduart** [comment]
Las opciones ya pueden deseleccionarse facilmente sin necesidad de mostrar la historia de busqueda
